language: generic 
sudo: required
servics:
  -docker

before_install:
  - docker build -t maimohammed907/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true maimohammed907/docker-react npm run test -- --coverage
